package exception;

/**
 * Created by bartoszpietrzak on 27/10/2017.
 */
public enum DigitalSignalProcessingErrorCode
{
	CALCULATION_DATA_NOT_PROVIDED,
	SIGNAL_TYPE_NOT_SUPPORTED,
	OPERATION_TYPE_NOT_SUPPORTED,
	SIGNAL_TYPE_NOT_GIVEN_BY_USER,
	SIGNAL_OPERATION_NOT_GIVEN_BY_USER,
	UNABLE_TO_CALCULATE_PERIOD_NUMBER,
	SAMPLES_AND_VALUES_DO_NOT_MATCH,

	SIGNAL_NOT_PRESENT_IN_REPOSITORY,

	UNABLE_TO_EXPORT_DATA_TO_FILE,

	UNABLE_TO_IMPORT_DATA_FROM_FILE,

	NO_SIGNALS_FOUND_IN_GIVEN_FILE,

	READ_WRITE_OPERATION_NOT_GIVEN_BY_USER,

	SIGNAL_SAMPLES_NOT_AVAILABLE,

	TWO_SIGNALS_NOT_SELECTED_FOR_OPERATION,

	TWO_SIGNALS_OPERATION_NOT_POSSIBLE,

	NO_SIGNALS_PRESENT_ON_SIGNAL_LIST,

	/**
	 * Quantization
	 */
	QUANTIZATION_TYPE_NOT_GIVEN_BY_USER,
	QUANTIZATION_TYPE_NOT_SUPPORTED,
	RECONSTRUCTION_TYPE_NOT_GIVEN_BY_USER,
	RECONSTRUCTION_TYPE_NOT_SUPPORTED,

	/**
	 * Filters
	 */
	FILTER_TYPE_NOT_FOUND,
	M_PARAMETER_NOT_PROVIDED,

	/**
	 * Unknown error
	 */
	SYSTEM_ERROR
}
