package exception;

/**
 * Created by bartoszpietrzak on 27/10/2017.
 */
public enum DigitalSignalProcessingErrorCode
{
	CALCULATION_DATA_NOT_PROVIDED,
	SIGNAL_TYPE_NOT_SUPPORTED,
	OPERATION_TYPE_NOT_SUPPORTED,
	SIGNAL_TYPE_NOT_GIVEN_BY_USER,
	SIGNAL_OPERATION_NOT_GIVEN_BY_USER,
	UNABLE_TO_CALCULATE_PERIOD_NUMBER,
	SAMPLES_AND_VALUES_DO_NOT_MATCH,

	SIGNAL_NOT_PRESENT_IN_REPOSITORY,

	SIGNAL_VALUES_NOT_AVAILABLE,

	SIGNAL_SAMPLES_NOT_AVAILABLE,

	TWO_SIGNALS_NOT_SELECTED_FOR_OPERATION,

	TWO_SIGNALS_OPERATION_NOT_POSSIBLE,

	/**
	 * Unknown error
	 */
	SYSTEM_ERROR
}
